# Generated by Django 5.0 on 2023-12-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_rename_message_chatmessage_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='history',
            field=models.JSONField(default='Another default value fam'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='response',
            field=models.JSONField(),
        ),
    ]
