# Generated by Django 5.0 on 2023-12-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_chatmessage_history_alter_chatmessage_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='question',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='userId',
            field=models.CharField(default='Yet another default value', max_length=36),
            preserve_default=False,
        ),
    ]
