# Generated by Django 5.0 on 2023-12-30 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_remove_chatmessage_question_chatmessage_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='userId',
            new_name='conversationId',
        ),
    ]
